name: Run RustDesk Flutter Build (stable)

on:
  workflow_dispatch: {}   # handmatige Run-knop

jobs:
  build-stable:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true     # upload per-platform artifacts
      upload-tag: stable        # prerelease tag-naam = "stable"
    secrets: inherit            # geeft repo-secrets (SERVER/KEY) door
