name: Build RustDesk (All Desktop + Android - per developer docs)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

env:
  RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
  RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}

jobs:
  linux:
    name: Linux (x64) - Flutter route
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@stable

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          flutter --version
          flutter config --enable-linux-desktop

      - name: Install build deps (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y universe
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev libayatana-appindicator3-dev \
            libwebkit2gtk-4.0-dev librsvg2-dev \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            cmake ninja-build pkg-config curl unzip \
            protobuf-compiler python3
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig" >> $GITHUB_ENV

      # FRB codegen per docs (pin naar 1.x zodat --rust-input werkt)
      - name: Install flutter_rust_bridge_codegen 1.80.1
        run: cargo install flutter_rust_bridge_codegen --locked --version 1.80.1
      - name: Run FRB codegen
        run: |
          flutter_rust_bridge_codegen \
            --rust-input ./src/flutter_ffi.rs \
            --dart-output ./flutter/lib/generated_bridge.dart

      - name: Flutter deps
        run: cd flutter && flutter pub get

      - name: Build (Linux)
        run: python3 ./build.py --flutter

      - name: Upload artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-linux-custom
          path: |
            ./rustdesk*
            ./flutter/build/linux/**

  windows:
    name: Windows (x64) - Flutter + vcpkg (per docs)
    runs-on: windows-latest
    env:
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - shell: pwsh
        run: |
          flutter --version
          flutter config --enable-windows-desktop

      - name: Install build deps (Windows)
        run: choco install -y git cmake ninja protoc python

      # vcpkg + libs zoals in de Windows build docs genoemd
      - name: Setup vcpkg
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg "$env:GITHUB_WORKSPACE\vcpkg"
          & "$env:GITHUB_WORKSPACE\vcpkg\bootstrap-vcpkg.bat"
          echo "VCPKG_ROOT=$env:GITHUB_WORKSPACE\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "VCPKG_DEFAULT_TRIPLET=x64-windows"      | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Install vcpkg packages (per docs)
        shell: pwsh
        run: |
          & "$env:GITHUB_WORKSPACE\vcpkg\vcpkg.exe" install `
            libvpx:x64-windows `
            libyuv:x64-windows `
            opus:x64-windows `
            aom:x64-windows
          & "$env:GITHUB_WORKSPACE\vcpkg\vcpkg.exe" list

      # FRB codegen per docs (pin naar 1.x)
      - name: Install flutter_rust_bridge_codegen 1.80.1
        run: cargo install flutter_rust_bridge_codegen --locked --version 1.80.1
      - name: Run FRB codegen
        shell: bash
        run: |
          flutter_rust_bridge_codegen \
            --rust-input ./src/flutter_ffi.rs \
            --dart-output ./flutter/lib/generated_bridge.dart

      - name: Flutter deps
        shell: pwsh
        run: cd flutter; flutter pub get

      - name: Build (Windows)
        run: python ./build.py --flutter

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-custom
          path: |
            .\rustdesk*.exe
            .\flutter\build\windows\**\*

  macos-intel:
    name: macOS (Intel, x64) - Flutter route
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@stable

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          flutter --version
          flutter config --enable-macos-desktop

      - name: Install build deps (macOS)
        run: |
          brew update
          brew install cmake ninja protobuf
          sudo gem install cocoapods --no-document

      # FRB codegen per docs (pin naar 1.x; voorbeeld toont ook c-output, maar niet strikt nodig)
      - name: Install flutter_rust_bridge_codegen 1.80.1
        run: cargo install flutter_rust_bridge_codegen --locked --version 1.80.1
      - name: Run FRB codegen
        run: |
          flutter_rust_bridge_codegen \
            --rust-input ./src/flutter_ffi.rs \
            --dart-output ./flutter/lib/generated_bridge.dart

      - name: Flutter deps
        run: cd flutter && flutter pub get

      - name: Build (macOS Intel)
        run: python3 ./build.py --flutter

      - name: Upload artifact (macOS Intel)
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-macos-x64-custom
          path: |
            ./flutter/build/macos/**/*
            ./rustdesk*.dmg
            ./rustdesk*.zip

  macos-apple:
    name: macOS (Apple Silicon, arm64) - Flutter route
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@stable

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          flutter --version
          flutter config --enable-macos-desktop

      - name: Install build deps (macOS)
        run: |
          brew update
          brew install cmake ninja protobuf
          sudo gem install cocoapods --no-document

      - name: Install flutter_rust_bridge_codegen 1.80.1
        run: cargo install flutter_rust_bridge_codegen --locked --version 1.80.1
      - name: Run FRB codegen
        run: |
          flutter_rust_bridge_codegen \
            --rust-input ./src/flutter_ffi.rs \
            --dart-output ./flutter/lib/generated_bridge.dart

      - name: Flutter deps
        run: cd flutter && flutter pub get

      - name: Build (macOS Apple Silicon)
        run: python3 ./build.py --flutter

      - name: Upload artifact (macOS Apple)
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-macos-arm64-custom
          path: |
            ./flutter/build/macos/**/*
            ./rustdesk*.dmg
            ./rustdesk*.zip

  android:
    name: Android (APK) - Flutter route
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@stable

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Android deps
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler python3

      # FRB codegen per docs (pin naar 1.x)
      - name: Install flutter_rust_bridge_codegen 1.80.1
        run: cargo install flutter_rust_bridge_codegen --locked --version 1.80.1
      - name: Run FRB codegen
        run: |
          flutter_rust_bridge_codegen \
            --rust-input ./src/flutter_ffi.rs \
            --dart-output ./flutter/lib/generated_bridge.dart

      - name: Flutter deps
        run: cd flutter && flutter pub get

      - name: Accept Android licenses
        run: yes | "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --licenses

      - name: Build (Android APK)
        run: |
          cd flutter
          flutter build apk --release

      - name: Upload artifact (Android)
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-android-apk-custom
          path: flutter/build/app/outputs/flutter-apk/app-release.apk
